mod day1;
mod day10;
mod day11;
mod day12;
mod day13;
mod day14;
mod day15;
mod day2;
mod day3;
mod day4;
mod day5;
mod day6;
mod day7;
mod day8;
mod day9;
mod utils;

fn main() {
    println!("Day 1");
    day1::run_easy();
    day1::run_hard();
    println!("\nDay 2");
    day2::run_easy();
    day2::run_hard();
    println!("\nDay 3");
    day3::run_easy();
    day3::run_hard();
    println!("\nDay 4");
    day4::run_easy();
    day4::run_hard();
    println!("\nDay 5");
    day5::run_easy();
    day5::run_hard();
    println!("\nDay 6");
    day6::run_easy();
    day6::run_hard();
    println!("\nDay 7");
    day7::run_easy();
    day7::run_hard();
    println!("\nDay 8");
    day8::run_easy();
    day8::run_hard();
    println!("\nDay 9");
    day9::run_easy();
    day9::run_hard();
    println!("\nDay 10");
    day10::run_easy();
    day10::run_hard();
    println!("\nDay 11");
    day11::run_easy();
    day11::run_hard();
    println!("\nDay 12");
    day12::run_easy();
    day12::run_hard();
    println!("\nDay 13");
    day13::run_easy();
    day13::run_hard();
    println!("\nDay 14");
    day14::run_easy();
    day14::run_hard();
    println!("\nDay 15");
    day15::run_easy();
    day15::run_hard();
}
